// In app/layout.tsx or app/layout.js
import type { Metadata } from "next";
import "./globals.css"; // Make sure this file is prepared to handle styles



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Google Fonts */}
        <link
          href="https://fonts.googleapis.com/css2?family=Figtree:wght@700&family=Montserrat:wght@400;500&family=Poppins:wght@400&family=Exo+2:wght@500&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={` antialiased`}>
        {children}
      </body>
    </html>
  );
}
